FROM node:lts-alpine AS build-env

WORKDIR /src
COPY . .

ARG WOP_HOST=wss://world.ptr.si/api
RUN yarn install && \
    yarn web build

FROM nginx:alpine

COPY --from=build-env /src/world-client/dist/ /usr/share/nginx/html
